<h1><center><br>Implementing an SVM Classifier<br></center></h1>

## Overview

In this project, you are going to implement SVM. For this purpose, a data set (data.mat) is given to you. You can load the mat dataset into Python using the function `loadmat` in `Scipy.io`. When you load the data, you will obtain a dictionary object, where `X` stores the data matrix and `Y` stores the labels. You can use the first 150 samples for training and the rest for testing. In this project, you will use the software package [`LIBSVM`](http://www.csie.ntu.edu.tw/~cjlin/libsvm/) to implement SVM. Note that `LIBSVM` has a [`Python interface`](https://github.com/cjlin1/libsvm/tree/master/python), so you can call the SVM functions in Python. 

## Task 1 - 30 pts

Train a hard margin linear SVM and report both train and test classification accuracy.

In [1]:
import scipy.io as sio
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
data=sio.loadmat("C:\\Users\\musat\\Desktop\\Yeni Klasör\\data")

from libsvm import svmutil 
from svmutil import*

In [2]:
dataY=data['Y']
dataX=data['X']
# splitting data into train and test part
trainX=dataX[:150,:]
trainY=dataY[:150,:]
trainY=np.reshape(trainY,150)


testX=dataX[150:,:]
testY=dataY[150:,:]
testY=np.reshape(testY,120)

In [3]:
HardMargin=svm_train(trainY,trainX,'-c inf -t 0')  # we take C value as inf since, hard margin requires no Error tolerance


In [4]:
print("Hard Margin SVM for training data \n")      # Test and Train ACC results
hardtrainresult=svm_predict(trainY,trainX,HardMargin) 
print("\nHard Margin SVM for testing data \n")
hardtestresult=svm_predict(testY,testX,HardMargin)  

Hard Margin SVM for training data 

Accuracy = 74.6667% (112/150) (classification)

Hard Margin SVM for testing data 

Accuracy = 77.5% (93/120) (classification)


## Task 2 - 40 pts

Train soft margin SVM for different values of the parameter $C$, and with different kernel functions. Systematically report your results. For instance, report the performances of different kernels for a fixed $C$, then report the performance for different $C$ values for a fixed kernel, and so on.

In [5]:
print("C value is fixed as 5, Kernel func is changeable.\n")
SoftMargin=svm_train(trainY,trainX,'-c 5 -t 0')     # Choosing C is 5 and trying model for different kernels 
print("For Linear kernel function ACC is ")         # Linear, Polynomial, RBF, Sigmoid
softtestresult=svm_predict(testY,testX,SoftMargin)

SoftMargin=svm_train(trainY,trainX,'-c 5 -t 1')
print("For polynomial kernel function ACC is ")
softtestresult=svm_predict(testY,testX,SoftMargin)

SoftMargin=svm_train(trainY,trainX,'-c 5 -t 2')
print("For RBF kernel function ACC is ")
softtestresult=svm_predict(testY,testX,SoftMargin)

SoftMargin=svm_train(trainY,trainX,'-c 5 -t 3')
print("For sigmoid kernel function ACC is ")
softtestresult=svm_predict(testY,testX,SoftMargin)

print("\nSigmoid is fixed as a kernel, C is changeable.\n")
                                                  #sigmoud function is fixed as a kernel func and we examine different C values 
SoftMargin=svm_train(trainY,trainX,'-c 3 -t 3')   # C values are 3, 6, 9, 12, 15.
print("For C=1 ACC is ")
softtestresult=svm_predict(testY,testX,SoftMargin)

SoftMargin=svm_train(trainY,trainX,'-c 6 -t 3')
print("For C=3 ACC is ")
softtestresult=svm_predict(testY,testX,SoftMargin) 

SoftMargin=svm_train(trainY,trainX,'-c 9 -t 3')
print("For C=5 ACC is ")
softtestresult=svm_predict(testY,testX,SoftMargin) 

SoftMargin=svm_train(trainY,trainX,'-c 12 -t 3')
print("For C=7 ACC is ")
softtestresult=svm_predict(testY,testX,SoftMargin)

SoftMargin=svm_train(trainY,trainX,'-c 15 -t 3')
print("For C=9 ACC is ")
softtestresult=svm_predict(testY,testX,SoftMargin)
 

C value is fixed as 5, Kernel func is changeable.

For Linear kernel function ACC is 
Accuracy = 81.6667% (98/120) (classification)
For polynomial kernel function ACC is 
Accuracy = 80.8333% (97/120) (classification)
For RBF kernel function ACC is 
Accuracy = 80% (96/120) (classification)
For sigmoid kernel function ACC is 
Accuracy = 82.5% (99/120) (classification)

Sigmoid is fixed as a kernel, C is changeable.

For C=1 ACC is 
Accuracy = 82.5% (99/120) (classification)
For C=3 ACC is 
Accuracy = 83.3333% (100/120) (classification)
For C=5 ACC is 
Accuracy = 84.1667% (101/120) (classification)
For C=7 ACC is 
Accuracy = 80.8333% (97/120) (classification)
For C=9 ACC is 
Accuracy = 82.5% (99/120) (classification)


## Task 3 - 15 pts

Please report how the number of support vectors changes as the value of $C$ increases (while all other parameters remain the same). Discuss whether your observations match the theory.

In [6]:
SoftMargin=svm_train(trainY,trainX,'-c 1 -t 0')
SV=SoftMargin.get_SV()
print("# of Support Vectors for C=1 is ",len(SV))

SoftMargin=svm_train(trainY,trainX,'-c 2 -t 0')
SV=SoftMargin.get_SV()
print("# of Support Vectors for C=2 is ",len(SV))

SoftMargin=svm_train(trainY,trainX,'-c 3 -t 0')
SV=SoftMargin.get_SV()
print("# of Support Vectors for C=3 is ",len(SV))

SoftMargin=svm_train(trainY,trainX,'-c 4 -t 0')
SV=SoftMargin.get_SV()
print("# of Support Vectors for C=4 is ",len(SV))

#number of sv is decreasing as we increase C value, it matches the theory
#because, as C increases error tolerance decreases so hyperplanes complexity decreases

# of Support Vectors for C=1 is  58
# of Support Vectors for C=2 is  56
# of Support Vectors for C=3 is  55
# of Support Vectors for C=4 is  54


## Task 4 - 15 pts

Please investigate the changes in the hyperplane when you remove one of the support vectors, vs., one data point that is not a support vector.

In [7]:
#linear full model no exclution
SoftMargin=svm_train(trainY,trainX,'-c 1 -t 0') 

#model that we exlude one support vector data point from dataset 
newtrainX=np.delete(trainX, 3, axis=0)
newtrainY=np.delete(trainY, 3, axis=0)
modelwithoutSV=svm_train(newtrainY,newtrainX,'-c 1 -t 0') 
 
#model that we exlude one non-support vector data point from dataset 
newtrainX2=np.delete(trainX, 6, axis=0)
newtrainY2=np.delete(trainY, 6, axis=0)
modelwithoutDP=svm_train(newtrainY2,newtrainX2,'-c 1 -t 0')
 
def findWandB(model):  # we make the calculations here to find w and b, by using coefficients and support vectors via libsvm
    b = model.rho
    b=b[0]*-1
    coef=model.get_sv_coef()
    SV=model.get_SV()
    SV_i=model.get_sv_indices()

    Matrix=pd.DataFrame(SV)
    Matrix=Matrix.fillna(0)
    Vector=pd.DataFrame(coef)
    colsize=len(Matrix.iloc[0,:])
    rowsize=len(Matrix)

    w=np.zeros([colsize-1,1])
    for j in range(colsize-1):
        sum=0
        for i in range(rowsize):
            sum+=Vector.iloc[i,0]*Matrix.iloc[i,j]
        w[j]=sum
    return w,b

In [8]:
findWandB(SoftMargin) # w and b values without exclution

(array([[-0.47637751],
        [ 0.39813231],
        [ 0.86713369],
        [ 0.57366213],
        [ 0.32304567],
        [ 0.10008082],
        [ 0.05139059],
        [-0.95512925],
        [ 0.07086555],
        [ 0.00576303],
        [ 0.24894908],
        [ 1.82218655],
        [ 0.5129991 ]]),
 1.1847368158140863)

In [9]:
findWandB(modelwithoutDP)  # w and b values without non-sv data point, as we can see excatly the same with full model 

(array([[-0.47637751],
        [ 0.39813231],
        [ 0.86713369],
        [ 0.57366213],
        [ 0.32304567],
        [ 0.10008082],
        [ 0.05139059],
        [-0.95512925],
        [ 0.07086555],
        [ 0.00576303],
        [ 0.24894908],
        [ 1.82218655],
        [ 0.5129991 ]]),
 1.184736815814086)

In [10]:
findWandB(modelwithoutSV) # w and b values without support vector data point, as we can see W and b is dramatically changed

(array([[-2.94880396e-01],
        [ 4.21184358e-01],
        [ 9.26642823e-01],
        [ 5.89842928e-01],
        [ 3.48248290e-01],
        [ 7.59411670e-02],
        [-1.41871622e-03],
        [-1.02161821e+00],
        [ 1.01050049e-01],
        [-1.44539506e-01],
        [ 3.02006450e-01],
        [ 1.81590860e+00],
        [ 5.11221871e-01]]),
 1.0716615962291343)

### Bonus Task - 10 pts

Use Python and [CVXOPT](http://cvxopt.org) QP solver to implement the hard margin SVM. 

In [11]:
import cvxopt
from cvxopt import matrix,solvers
from cvxopt.solvers import qp
  

In [12]:
Xtoy=[0,0,2,2,2,0,3,0] # we upload the example in class
Xtoy=np.reshape(Xtoy,(4,2))
Ytoy=[-1,-1,1,1]

Q=np.zeros([3,3])  #creating Q,p,A,c matrices  
for i in range(3):
    for j in range(3):
        if(i==j and i!=0):
            Q[i][j]=1

p=np.zeros([3,1])
c=np.ones([4,1])

A=np.zeros([4,3])
 
for j in range(3):
    for i in range(4):
        if(j==0):
            A[i][j]=Ytoy[i]
    
        else:
            A[i][j]=Ytoy[i]*Xtoy[i][j-1]
    




U=solvers.qp(matrix(Q),matrix(p),matrix(-1*A),matrix(-1*c))

     pcost       dcost       gap    pres   dres
 0:  3.2653e-01  1.9592e+00  6e+00  2e+00  4e+00
 1:  1.5796e+00  8.5663e-01  7e-01  0e+00  2e-15
 2:  1.0195e+00  9.9227e-01  3e-02  1e-16  1e-15
 3:  1.0002e+00  9.9992e-01  3e-04  2e-16  2e-15
 4:  1.0000e+00  1.0000e+00  3e-06  3e-16  7e-16
 5:  1.0000e+00  1.0000e+00  3e-08  4e-16  7e-16
Optimal solution found.


In [13]:
pd.DataFrame(U['x'])  # we get results as we expect b*=-1 w*=[1,-1]

0
0 -1.0
1  1.0
2 -1.0